name: Build RISC-V ISA simulator (Spike)
on:
  push:
  schedule:
    - cron: '42 20 * * 2,4,6'
jobs:
  build_doc:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v6

      - name: Clone spike source
        run: |
          git clone https://github.com/riscv-software-src/riscv-isa-sim.git

      - name: Install build-time dependencies
        run: |
          dnf install dtc

      - name: Build spike
        run: |
          cd riscv-isa-sim
          mkdir build && cd build
          ../configure --prefix=/opt/riscv
          make -j`nproc`
          make install

      - name: Post-build check
        run: |
          ls -lR /opt/riscv
          ldd /opt/riscv/bin/*
